# Generated by Django 6.0.5 on 2026-07-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bio_customuser_phone_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
